### ISSUE TITLE
Content store: Disallow WTFPL licenses to help use of MT in schools

### ISSUE THREAD

**Issue by paramat** [minetest/contentdb#107]
We removed all WTFPL licenses from MTG as the 'F' word can get teachers into serious trouble, or even fired. MT cannot be used in schools if a package containing a WTFPL license is downloadable in the content store. I guess MT would mostly not be used connected to the internet, but it probably will be sometimes.

Would have a useful side-effect as an incentive for modders to stop using such a problematic license that also has no disclaimer.

**Comment by rubenwardy** [comment]
The problem with this is when a mod's author is no longer around to change the license

**Comment by paramat** [comment]
WTFPL allows anyone to fork the mod and change the license to MIT. If the author is absent and the mod is not forked and maintained it will have other bigger problems too such as not being updated. So this seems a non-issue and of less significance than the schools problem.

**Comment by Wuzzy2** [comment]
Woah, woah, woah, isn't that an extreme measure?

You are about to ban a lot of mods. Proceed with care.

Also, you are going a dangerous route here … If you are starting to try to obey the draconian rules of every organization (yes, I think the “anti fuck rule” IS draconian), you will eventually ban way more mods.

If the Kingdom of Tyrannia forbids the use of LGPL, should we change the license only to please them?

My point is, there will *always* be people who take offense for any reason. If you try to please everyone, you will fail epicly.

**Comment by sofar** [comment]
I've done this exact thing (change license) before merging an abandoned mod into minetest-mods. Please feel free to ask if you need this for another mod.

**Comment by appgurueu** [comment]
I have to say that I used WTFPL many times already.
And others did so too, so please don't ban it.
I'll probably change it, however.

**Comment by Wuzzy2** [comment]
For the record, I agree with some the *practical* arguments for avoiding the WTFPL as a creator.

So I am fully onboard of *discouraging* the use of the WTFPL, but not for outright *banning* it. Minetest should not be the extended arm of draconian school rules.

Silly idea: If this bugs you so much, would it be possible to write a bot that automatically changes a mod's license from WTFPL to MIT License when it's uploaded to Content DB?

**Comment by paramat** [comment]
I completely agree with sofar.

Wuzzy2 it's easy to update a license from WTFPL to something else, anyone can do it whether they are the author or not, and it moves a modder to a safer license with a disclaimer. So essentially it simply helps a lazy modder by creating more reason to do the right thing which is good for them in the end. I wish i had been encouraged to move away from WTFPL earlier.

If a mod is in the content store it should obviously be held to higher standards.

I think there was a poll run recently somewhere (twitter?), the result was using MT for education was the highest usecase for MT.
> Also, you are going a dangerous route here … If you are starting to try to obey the draconian rules of every organization [...]

It's not dangerous at all because we won't, we would judge each situation carefully and we know when to draw the line. Usage in education makes this completely justified. Keep in mind WTFPL is a bad license that is open to legal abuse, and the F word has absolutely no benefit whatsoever to MT. There is no defence.
If many mods use WTFPL that's just too bad, they soon won't if they want to be in the content store.
> If the Kingdom of Tyrannia forbids the use of LGPL, should we change the license only to please them?

No obviously.
> My point is, there will always be people who take offense for any reason. If you try to please everyone, you will fail epicly.

I totally agree, but irrelevant. Think practically.
> So I am fully onboard of discouraging the use of the WTFPL, but not for outright banning it.

Unless it's strictly banned from the store the whole effort is pointless. Your arguments are extreme, ridiculous, idealistic and impractical.

**Comment by Wuzzy2** [comment]
Is there really no concern that you are about to ban a large number of mods and piss off the modding community? :-(

Also, I disagree with the absurd claim that education is the number one use case for Minetest. No, it's not. Playing games is the number use case. Evidence: Just look at all mods, games and servers and count how few of them are education-related.

**Comment by sofar** [comment]
Nobody made any claim that education being the number one use case.

**Comment by sofar** [comment]
> Is there really no concern that you are about to ban a large number of mods and piss off the modding community?

There is a concern that you are taking this discussion too far long the path where you attempt to make good willing people look bad based on your viewpoint, since that is the only *effect* you can have.

Your points are noted. The discussion is over. Agree to disagree? But please, stop attempting to find yet another angle of the same discussion point.

Note: I see no reason for now to ban WTFPL from the forums. This is about contentdb, specifically. Although honestly I think getting everyone to relicense their code to an actual license would be good, for the aforemented reasons as to why WTFPL is a bad license to begin with.

**Comment by Warr1024** [comment]
The simplest solution here seems to be to ask the author what the mod's _original_ license agreement is.  If they choose any option that is not allowable, such as WTFPL (due to "offensive content" restrictions MT may be exposed to) or "Public Domain" (due to issues with certain jurisdictions not recognizing it properly) then ContentDB can exercise any rights its _own_ authors are granted under that license to automatically upgrade the license to an acceptable one.  Modders wouldn't need to change their licenses (though they could still be encouraged to do so), contentdb can still benefit from the widest selection of content possible, and offensive, dangerous or otherwise deprecated licenses can be for the _most part_ avoided.

You'd probably want to have a disclaimer appear when someone selects a deprecated license that warns them about the automatic sublicensing, i.e. "By choosing this, you are granting the authors of ContentDB permission to relicense your content under the terms of the MIT license.  You may still license your work under the original terms via other distribution channels, though you should consider changing to a different license anyway, and here's a link to our guide explaining why."

**Comment by paramat** [comment]
@rubenwardy please could you explain why this was closed? I'm not too bothered but it seems to be somewhat supported by sofar too.

**Comment by paramat** [comment]
@rubenwardy ^

**Comment by paramat** [comment]
@rubenwardy ^

**Comment by sofar** [comment]
>  Modders wouldn't need to change their licenses

This just prolongs the problem and makes contentdb difficult to use for them.

But the biggest problem is that now there are 2 versions of the software with different licenses available, with potential legal problems due to confusion.

Besides, there is no way to `automatically` relicense things on contentdb. Overwriting the files in releases isn't doable (either from a technical but also from a legal perspective).

So, while the idea would be great, I think we should say "no" to this entirely.

**Comment by paramat** [comment]
Unfortunately this issue wasn't attended to when i opened it. I intentionally opened it before the CDB has mods added to it, to avoid the problem of what to do with mods already added =)

**Comment by sofar** [comment]
Well, let's work with the authors to fix it, and if they are not responsive, we'll want to remove the affected mods.

**Comment by rubenwardy** [comment]
I forgot to respond to your message when you posted, and don't have time right now

**Comment by paramat** [comment]
Ok. Thanks for the reopen =)
> The problem with this is when a mod's author is no longer around to change the license

Unmaintained mods will need to be forked and maintained sooner or later anyway, the license can be changed then.
I think unmaintained mods with WTFPL licenses don't meet the minimum quality standard for CDB.
> The simplest solution here seems to be to ask the author what the mod's original license agreement is. If they choose any option that is not allowable, such as WTFPL (due to "offensive content" restrictions MT may be exposed to) or "Public Domain" (due to issues with certain jurisdictions not recognizing it properly) then ContentDB can exercise any rights its own authors are granted under that license to automatically upgrade the license to an acceptable one. Modders wouldn't need to change their licenses (though they could still be encouraged to do so)

That seems messy. Also, it's better for the modder if they are encouraged to change the license of their original mod to one with liability protection.
//////////////////////////

I suggest this:
If a WTFPL mod is maintained, the maintainer is asked to change the license before it can be added to the CDB.
If a WTFPL mod is unmaintained, fork it (which will need to be done sooner or later anyway), change the license, then add it to CDB.

And i request that, from now on, no mod with WTFPL is added to the CDB. Some already have been, for those, i suggest we ask the modder to change the license within a few months if they want the mod to stay on CDB.

I think it's important to realise that everyone benefits, including the modder, from not using WTFPL. I don't accept the idea pushed by some that somehow modders will suffer. I wish i had been encouraged to stop using WTFPL earlier.

**Comment by Wuzzy2** [comment]
Am I the only one who finds it hilarious to what great lengths you now go to ban only one specific, particular and (IMHO) relatively harmless license while you all keep ignoring the elephant in the room, which is proprietary licenses that restrict usage (which do REAL damage), which you still allow to this day.

Not that I really shed a tear after the WTFPL anymore (there are enough alternatives like the MIT License), I'm just pointing out the huge irony here. :P

**Comment by sofar** [comment]
@Wuzzy2 

> while you all keep ignoring the elephant in the room, which is proprietary licenses that restrict usage (which do REAL damage), which you still allow to this day.

Please, OPEN A NEW BUG. (I don't even know what license you're talking about and I do NOT want you to write about that in THIS thread. Take the time to open a new bug please).

Maybe it is something we can solve in 5 minutes, but, the problem is not entirely the same, and it deserves it's own thread.

Let's keep this thread focused on WTFPL and discuss other licenses separately.

**Comment by rubenwardy** [comment]
I think that Wuzzy's post is relevant to this discussion, as it points out the hypocrisy

**Comment by Wuzzy2** [comment]
@sofar: There you go: https://github.com/minetest/contentdb/issues/151

**Comment by paramat** [comment]
It's not 'hypocrisy', both are valid issues. Here we're dealing with WTFPL, deal with proprietary licenses in another issue.
I'm neutral about banning proprietary licenses so i can't be hypocritical on this.
The WTFPL license does 'REAL' damage to the use of MT in schools (which is a surprisingly large usage of MT) and if someone decides to sue you.
