### ISSUE TITLE
Release list sidebar in package detail page gets too long.

### ISSUE THREAD

**Issue by Warr1024** [minetest/contentdb#126]
Packages with a lot of releases, like https://content.minetest.net/packages/Chiantos/blockcolor/, end up with a kind of ridiculous layout with a ton of releases in the sidebar.

We should probably limit the number shown on initial page load, and if not all fit within that limit, have a "show more..." link.  That link could either extend the sidebar, or go to a separate page.

**Comment by Linuxdirk** [comment]
Extending the `.list-group` definition in the CSS with the following two attributes makes the list scrollable and shows roughly the most recent 2-3 releases

```css
    max-height: 200px;
    overflow: auto;
```

Height is debatable and there might be a better location in the CSS, but hey 😃 Because auf `max-height` the list will be smaller if there are less releases and will extend up to the given value and then adds scroll bars.

**Comment by rubenwardy** [comment]
https://github.com/minetest/contentdb/commit/7e4eb29db7dbaed9e5fb8001e90833aeef8bbfd9
