### ISSUE TITLE
Improve popular/trending heuristic

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#154]
Requirements:

* Needs to not depend on forum topics
* Make it possible for packages newer than 2016 to get into the featured section
* ...

To implement this, edit `Package.recalcScore()` in app/model.py. It may actually be worth separating this into two scores - an all-time popular score, and a trending score. If the algorithm used is time-dependent, then you can use a celery beat task to update it.

**Comment by rubenwardy** [comment]
Related #155

**Comment by LoneWolfHT** [comment]
Maybe the mod with the most downloads in the past month/two weeks?

**Comment by Warr1024** [comment]
The primary goal here should be to expose users to packages they may find interesting.  The secondary goal should be to try to get packages about which we don't know as much more exposure, so we can learn what kind of quality they possess.

The current heuristic, using forum activity, is misleading because newer packages are coming out that are not represented on the forums, or don't use the forums as a central point of communication and thus don't generate as much activity there.  Using download counts would be misleading because it penalizes packages that are multiplayer-centric (such as CTF) or for which large multiplayer servers exist that obviate downloads.

Coming up with a good meaningful metric would be difficult, and highly bikesheddable.

One alternative, at least as a stopgap, would be to just pick a uniform random sample every day or so of packages in each category to be "featured."  In the absence of raw data that can be used to indicate quality (i.e. we know how many people tried a package, but not how many liked it, so we only know the quality of the sales pitch, not the product) random selection would at least be fair.

**Comment by rubenwardy** [comment]
33b2b38308c41fc9d182df241a317f700d861d9a
