### ISSUE TITLE
Prevent download stat manipulation

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#155]
It is currently possible for malicious users to spam the download endpoint to inflate their scores

**Comment by LoneWolfHT** [comment]
Only count an IP's download once?

**Comment by rubenwardy** [comment]
that's the solution. I need to find a technology to do that effectively

**Comment by SmallJoker** [comment]
You could change the counting mechanism so that it relies on a static counter and dynamic IP-duplication checker:
1) IP-duplication checker: Keep unique IPs per mod for a week
   * Refresh the timestamp if they re-download it during that week:
   * `old_timestamp + (new_timestamp - old_timestamp) * 0.5` so that it expires faster afterwards
2) When the IP record expires, increase the static download counter
3) For the displayed count: Sum up the static counter and entries of the IP duplication checker.

You could keep each user's IP for a month (in a database). As soon it expires, increase the

**Comment by Warr1024** [comment]
The easiest way to prevent people from inflating download counts is to make them meaningless by providing a more meaningful metric for package owners to want to maximize.

**Comment by rubenwardy** [comment]
https://github.com/minetest/contentdb/commit/ff2a74367f3fe980f08c20c691d451d1ae55b95a
