### ISSUE TITLE
Add maintainer field to give another user owner rights over a package

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#159]

**Comment by S-S-X** [comment]
Not sure if this is correct place to mention this but issue description is a bit vague :smile: 

Could there be user *list* to give other users access, there would be real use case for multiple maintainers who would like to share contentdb account? In other words: allow multiple users to maintain single contentdb package.

Currently way to go was using shared pseudonym user account for contentdb but that really is not best way to do it because:
* everyone shares data on single account
* password has to be shared
* all other problems that will arise from mentioned ones

In short it would be nice to have ability to link other user accounts to one account, kinda like having contentdb project where multiple user can contribute / update package data and screenshots / manage API keys and stuff like that.

Few possible ways I can think of to implement at higher level (pick one or none):
* Ability to impersonate other user if you are in other user's maintainer list.
* Ability to create project which are similar to users but are owned and other users can be invited.
* Direct access to all data of other user account if you are in other user's maintainer list.

**Comment by rubenwardy** [comment]
This makes a lot of sense

**Comment by rubenwardy** [comment]
![image](https://user-images.githubusercontent.com/2122943/86973696-e9b7ff80-c16c-11ea-9e25-5cffc7188faa.png)
