### ISSUE TITLE
Add state field/tag/flag to store WIP/Beta/Stable/Mature/Abandoned

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#160]

**Comment by Warr1024** [comment]
Rather than a single-select for a specific state (the members of which we could argue about) I think I'd rather see this handled sort of like the content warning flags.  For example, WIP packages could be flagged with a "Warning: Incomplete" flag that users could filter by, while abandoned packages could be flagged with "Warning: Unmaintained."

There are certainly packages that demonstrate that (1) these states are not mutually exclusive, i.e. something can be both WIP _and_ abandoned, and (2) the states are not necessarily a series or continuum either, since a package could become abandoned, but then re-adopted, maybe even by the original creator who has a change of heart.

Using the existing flag system would also simplify the implementation since we wouldn't have to add a new field or new filtering capabilities.

I very rarely ever see open source software projects (as a majority of CDB packages should be) that can make a stable and meaningful distinction between states like "beta", "stable", or "mature".  Often "perpetual beta" is the stable state of open-source projects, including ones that see extensive production use, and "stable" or "mature" is usually more a matter of opinion that would be better handled by an end-user review process rather than a creator's assertion.

**Comment by Warr1024** [comment]
My suggestion to use tags is very similar to https://github.com/minetest/contentdb/issues/210.

The main difference I think is that tags for curation may need to be managed by editor or other higher-ranked users as a matter of fiat for curating the suggested package list, while the tags I'm suggesting in https://github.com/minetest/contentdb/issues/160#issuecomment-753024390 would be managed by the package author to make assertions about the package's state without the need for editor intervention.

**Comment by Calinou** [comment]
Can we use something akin to the [maintenance status in `Cargo.toml`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section)?

**Comment by rubenwardy** [comment]
![image](https://user-images.githubusercontent.com/2122943/146830483-18c689a3-43ef-4f1b-a156-62730c2e08d3.png)



![image](https://user-images.githubusercontent.com/2122943/146830495-0a02d4bf-d9ed-413c-93f7-7b2c4c07f922.png)

**Comment by rubenwardy** [comment]
![image](https://user-images.githubusercontent.com/2122943/146833031-2d7f332b-38a8-45ae-ba50-9f0d234c4d0c.png)

**Comment by Wuzzy2** [comment]
Thank you! I have to remember to update my package states eventually.
