### ISSUE TITLE
Support texture pack completion check

### ISSUE THREAD

**Issue by tacotexmex** [minetest/contentdb#163]
Once there was [this tool](https://github.com/dolanmiu/Minetest-Texture-Pack-Completion-Checker) that checked the available filenames in a texture pack in comparison to the complete texture filename list of MTG. This would allow for checking how complete the pack was. (Since then, subfolders in TPs got supported which breaks this particular implementation)

A similar thing inside contendb would be useful. This will of course require the TP to be associated with a list of optional dependencies and the texture filenames of those dependencies, and so some deep repo inspection will be required.

**Comment by rubenwardy** [comment]
I think this would be better as a separate service. The link you gave already has that service, it could then be integrated with ContentDB a little better I guess

**Comment by tacotexmex** [comment]
Sure, it can be a separate service but it needs maintenance, which this service doesn’t receive.

**Comment by Df458** [comment]
I don't think this approach will work 100%, unfortunately. Because there are cases where mods define unused textures, or `overrides,txt` replaces the use of one texture for another, the numbers will probably be hard to determine accurately.

With that said, it could still be useful if it was an imprecise rating (ie. cutting the percentage into ten 'tiers' instead of displaying a precise value), and being able to say more 'officially' what a texture pack supports could be interesting as well.

**Comment by tacotexmex** [comment]
I realized this too, and a tier rating would still be beneficial to users. 👍

**Comment by rubenwardy** [comment]
The tool could be given an overrides file that contains the source textures for each mod and game. For each mod and game,  the texture packs override will be applied over the source and then used to check for the existence of files in the texture pack

**Comment by Df458** [comment]
The problem is, `override.txt` doesn't operate on textures--it operates on specific node (and item, if I get my way) definitions. This is harder to test, because we don't know these definitions without running the lua code (for instance, Nodecore generates most definitions). I can't say that it would be *impossible* to test, but I suspect that getting a precise result would require a rather complex tool.

**Comment by rubenwardy** [comment]
> it operates on specific node (and item, if I get my way) definitions. This is harder to test, because we don't know these definitions without running the lua code

This is where the mod and game overrides comes in - it would be a list of the textures for each node, generated by a mod
