### ISSUE TITLE
.gitattributes export-ignore does not work correctly

### ISSUE THREAD

**Issue by Warr1024** [minetest/contentdb#184]
Some files that are supposed to be excluded from git archives (and thus from CDB release downloads) are being included.

Upstream issue: https://github.com/Kentzo/git-archive-all/issues/78

git-archive-all development seems to follow a pretty long time-scale, so we shouldn't expect a fix for quite some time.  In the meantime, archives for some packages are orders of magnitude larger than they should be, due to excluded files, so a workaround in CDB would be welcome.

One thing we could try is detecting submodules and only using git-archive-all for packages that use submodules, falling back to plain git-archive for others.  This would improve the situation for at least _some_ packages.

**Comment by rubenwardy** [comment]
fixed upstream

**Comment by doxygen-spammer** [comment]
For completeness: *not* fixed upstream, and probably won’t ever be.
See Kentzo/git-archive-all#87.

As workaround here, you have to write the .gitattributes file such that `git check-attr` returns the desired attributes for all files.
Instead of `some/dir/` you can try `some/dir/**`, `/some/dir`, and `**/some/dir`; depends on your directory layout.
