### ISSUE TITLE
How to handle game compatibility? Be stricter on game mod names?

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#221]
Currently, games are less moderated when it comes to reusing existing mod names.

This leads to games like repixture reusing the modname "default", which becomes a nightmare when you want to detect which games a mod supports.

Proposals:

- Forbid new games from reusing mod names where they don't follow rule 3.2.
- Forbid all games, unapprove existing games.
- Give up, add another field for mods to specify their own compatibility with games. This would make filtering by game much much easier

/cc @Wuzzy2 @warr1024

**Comment by Wuzzy2** [comment]
Forcing games to change all their mod names to globally unique names is not a practical solution. A lot of mods in games are copies from a particular standalone mod posted in the forums, but the APIs/features will naturally diverge over time. Also, for mod authors its much harder to check for name collisions with literally all game modes than just checking for standalone mods. Also, changing important game mod names can be highly disruptive, meaning you need to touch a lot of code … It's not like it cannot be done, it's just that it's a HUGE pain in the ass.

(BTW: The only reason why I haven't dropped the name “default” in Repixture is because I released version 1.0.0 with this mod, which means I can no longer change the name. If I do, I will break worlds, which is a no-go.)

Also, Repixture is far from the only game that has `default`, basically most MTG forks do have MTG mod names, even if the mods are radically different. And it's not just `default`. 

Important fact: Mods in a game are somewhat special … As those are mods that are specific for that game. Often enough, you can't just rip out random mods from a game and make them standalone. It's common and often required to tweak mods for the game, so the original standalone is technically no longer there but pedantically would require a rename.
A `stairs` mod in game A might still be different in game B, even if both are MTG-derived, the API difference could come simply from different versions. Let's be real, MTG has no ownership of the name `default`, this battle has been lost long time ago.

Therefore, trying to make all games comply is just not going to work. But maybe we don't need to do that, because of the special role of “game mods”. Since game mods are in a special role, they should not be subject of the same rules for standalone mods.

I have a different idea:

Add support (in Minetest) for a special dependencies syntax, it looks like this: `mygame/modname`, where “mygame” is the ID of the game, and `modname` is the ID of the mod. If you write a dependency like this, it means the mod depends on a mod as specifically provided in a game. This also implies the addition of game IDs (which Minetest doesn't support yet).

For example, if you write `minetest_game/default` into the dependencies (instead of just `default`), this means the mod depends on `default` from Minetest Game.

**Comment by benrob0329** [comment]
> Also, Repixture is far from the only game that has default

So you're saying you're part of the problem? :P

> A lot of mods in games are copies from a particular standalone mod posted in the forums, but the APIs/features will naturally diverge over time.

Then they shouldn't keep the same name, as they aren't the same mod. Part of CDB is making a cohesive packaging system, and either maintaining compatibility or changing the name is part of that.

> BTW: The only reason why I haven't dropped the name “default” in Repixture is because I released version 1.0.0 with this mod, which means I can no longer change the name. If I do, I will break worlds, which is a no-go.

This sounds like a case for either keeping item names the same, or setting up aliases (which can be done with a small script or decent text editor easily).

> A stairs mod in game A might still be different in game B, even if both are MTG-derived, the API difference could come simply from different versions.

Then maybe game B shouldn't keep that mod name, since mods depending on it will fail.

It's really quite easy to use a naming prefix for your game (`nc_*`, `ikea_*`, even `mtg_*` wouldn't be a difficult change), which lets mods cover for differences between versions.

> Add support (in Minetest) for a special dependencies syntax, it looks like this: mygame/modname

Having said all of that, giving games their own namespace by default would be great and removes a lot of problems, but still requires everyone to update their dependancies.

**Comment by benrob0329** [comment]
My opinion on this is largely the same. I'd argue that unapproving games which break compatibility with existing mods is a fair way of enforcing this. We have to be able to move forward sometimes.

Also having a policy for games which "steal" another game's namespace (like if IKEA were to make a new `nc_furniture` mod for some reason, and remove Nodecore's ability to do the same despite Nodecore having established that namespace beforehand) might be a good idea.

**Comment by rubenwardy** [comment]
Please see the linked issue in the Minetest engine

And for the record: ContentDB's current policy is to not let in new games that break the mod name uniqueness rule, instead asking them to use namespaces. Existing games haven't been unapproved/asked to change modnames
