### ISSUE TITLE
Automatically make releases on new git commits

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#50]

**Comment by Warr1024** [comment]
I disagree with the "should still be approved."  If a package author has configured their package for automatic releases on commit, then that, plus the presence of a commit, already constitutes all the approval necessary.  If authors want to be able to work on things without triggering a release then they need to exercise proper branch discipline, or simply not use the feature.

Also, the rate limiting is probably not a bad idea, but "once a week" is at least 2 orders of magnitude too long an interval.

Not being a texture pack creator myself, I intend to use this feature for games and mods.  This feature can make sense for any package depending on the author's release cycle, independent of package type.

**Comment by sofar** [comment]
Perhaps it's a lot better to trigger based on tags/releases, then on git commits. We'd like to encourage people to make tags, this could be helpful.

**Comment by Warr1024** [comment]
Tags should generally be significant, and their use should only be
encouraged for projects whose releases are sufficiently far from 1:1 with
commits.

Making this an option for those kind of workflows might be nice, but on the
other hand I wouldn't want to clutter contentdb up with a ton of options.
We don't really need to be able to enable spacebar heating.

To be fair, many of us could probably adapt to either workflow.  Just takes
a few scripts...

**Comment by Linuxdirk** [comment]
Tags are nice but forcing them seems not to be the right way. This forces authors into a specific release concept they might not want.

With a forced release system (tags, "releaes", etc.) adding stuff to the CDB feels like a burden (generate or make up a version number, taking SemVer into consideration, etc.) instead of simply pushing changes to the Git repository if wanted.

I think a better solution would be having stuff in the CDB automatically. Maybe check for changes on a weekly basis and automatically create and publish a new version.

**Comment by Warr1024** [comment]
If you're talking about a use-case for packages that are being actively developed but whose authors are not keeping up their CDB listings, then a weekly scan of everything we have a repo URL for would make some sense.  In those cases, though, unless the author consents to (i.e. configures) an automatic release, then all CDB would be able to do is nag them.

The use-case I'm more concerned with is when I'm doing active development and want my updates to make it onto CDB _promptly_.  A weekly scan will not solve that problem; an hourly scan would barely be adequate.  The need may be better served by providing an API endpoint that would allow me to setup my own automation.

The API option would also work better for me because I need to run some lua code to calculate the version numbers for my releases, and that would allow me to have the release names on CDB match the actual version numbers within the package.

**Comment by rubenwardy** [comment]
> would allow me to have the release names on CDB match the actual version numbers within the package.

This sounds like a good usecase for tags, to me

**Comment by Warr1024** [comment]
In the meantime, I've created a script that allows package owners to create releases from the command line, or from a script.  This could be a building block for a daemon or a git hook script.

https://gitlab.com/sztest/cdbrelease

Since package owners can run this script themselves, it also takes away the variable of timing and allows them to have exactly the release schedule they want.

**Comment by Warr1024** [comment]
On the subject of tags, they do sound like they really fit certain aspects of the need very well.  I've never really used them before, but it may be time that I learn; the immutability of them is a little daunting.

There are complications, though.

With branches, you always know exactly what ref you're publishing, and you know what the latest commit is (i.e. the one the branch is pointing to _now_).  When using tags, it's non-trivial to tell what branch a tag "belongs to" (the concept is not fully valid in git) and which tag is the "latest" version in that series.  Whether we publish only the latest tag on a rolling basis, or whether we publish every tag we haven't published so far, we still need to be able to put them in sequence.

You can't necessarily count on a package owner using tags ONLY to indicate things intended for CDB release.  They may have other internal use for tags.  There are also tools that I've used that create tags automatically, e.g. when importing from another source control system, they use tags to indicate the identifier for the revision in the original source control system so they can be cross-referenced.

**Comment by Linuxdirk** [comment]
> On the subject of tags, they do sound like they really fit certain aspects of the need very well.

Yes, tags are great if your development is release-based. Just code and commit whatever you want, and when SemVer "demands" a version number change or when you feel like the current version is different enough from the previous version to get a new version number, just create a tag and push that to the repository.

If you develop and publish in rolling release tags are a burden and just feel forced. I only use tags for my mods to define a commit to which the mods work with older Minetest versions. So "forcing" tags for releases on CDB would cause my mods having exactly one release at the end of support for the previous Minetest version.

One thing that I might look into would be using GitLab/GitHub CI to push to the CDB after pushing the commits to the repo (or the `post-update` hook when running an own Git server).

**Comment by rubenwardy** [comment]
This is now implemented
